language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services:
    - docker
    env:
    - BASEEXE=stockfish
  - os: osx
    compiler: gcc
    env:
    - COMPILER=g++-4.8
    - COMP=gcc
    - BASEEXE=stockfish-osx

before_install:
- ldd --version || echo no ldd
- if [ -f /proc/cpuinfo ] ; then cat /proc/cpuinfo; fi

script: |
  if [ "$BASEEXE" != "stockfish-osx" ]; then
    docker build --tag wheezy-for-stockfish .
    docker run --volume $PWD:/home/builder/Stockfish --user $(id -u) wheezy-for-stockfish
  else
    ./unix_build.sh
  fi
  ls -lh

deploy:
  provider: releases
  api_key:
    secure: Syi4MLMPTt+p3MOcSpg3goBU80Nt/aqhmvhnE6BLrwaKXg40fTA/swBeNcKsV+wxAFkI8QjAi/IYS9xuNBN4lOZ7TbC8ICEDzPfq+jIhlMWJZPbWxXZxMnhXdqQv0Ohw1C7SyPNcLDzYKGaawNbuvVHnV64s4mTak5lS/lz9NU3jgj4ZEhp4mSCB6cwkiqJG0EzCszx93KK6bVnGLXSQRO+MmZEnoSksA790OFUuMhasokqHkIkhDCy5HZ6cHFGRCdZ1xWPSnhOOjIP10j6E1aXKaRBKL7XdFWGeFM7bXSmZf+X3uWIZ+lP8w5gBEpkFRzmjgGGH7lriZ0wim65jJAQ9NaDINPGwYE96yfbIVN+yHqXcKPc6PboHntV70hUxfOEYWeOFrHYCzlXfwN1MenwmmDJhT2bwoSAqO8jdaoczPLX+z4J0fP/19TI9ULSM8IwYOxWyOHUagtQ9ouZURrO402iptNdCDxjHNiYjtCAl34JvwVDnHqbHE1woy9nyoHDobNFdeID6nsBXdugVVzmh1WTG41vOW+qbU4XqMv+fAbVWnosCIuUZu2hpz97vOXT7AZUoTvAM3zKsl46pmELzufM5z2pCupOOsUaV1+va1NkGygnKC3r7QKEgAi1sMq7146qsvHLaV5yJ74Z0avWn18cFntnjaqGI3X9hAC8=
  prerelease: true
  file_glob: true
  file:
    - $BASEEXE-*
  skip_cleanup: true
  on:
    tags: true
    repo: niklasf/Stockfish
    branch: fishnet
